USE fantasydata;

SELECT t1.POSITION, t1.NAME, t1.tot_points
FROM (
    SELECT POSITION, NAME, SUM(FPTS) AS tot_points
    FROM tb
    GROUP BY POSITION, NAME
) AS t1
JOIN (
    SELECT POSITION, MAX(tot_points) AS max_points
    FROM (
        SELECT POSITION, NAME, SUM(FPTS) AS tot_points
        FROM tb
        GROUP BY POSITION, NAME
    ) AS t2
    GROUP BY POSITION
) AS t3 
ON t1.POSITION = t3.POSITION AND t1.tot_points = t3.max_points;



WITH RankedData AS (
    SELECT
        NAME,
        TEAM,
        POSITION,
        SUM(FPTS) AS TOTAL_POINTS,
        SUM(PASS_TD + RUSH_TD + REC_TD + MISC_TD) AS TOT_TD,
        ROW_NUMBER() OVER(PARTITION BY POSITION ORDER BY SUM(FPTS) DESC) AS PointsRank,
        ROW_NUMBER() OVER(PARTITION BY POSITION ORDER BY SUM(PASS_TD + RUSH_TD + REC_TD + MISC_TD) DESC) AS TDRank
    FROM tb
    GROUP BY NAME, POSITION, TEAM
)
SELECT
    NAME,
    TEAM,
    POSITION,
    TOTAL_POINTS,
    TOT_TD
FROM RankedData
WHERE PointsRank <= 6 OR TDRank <= 6
ORDER BY POSITION, PointsRank, TDRank;
